@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

ComponentDb(database,"Database")

System_Boundary(APISystem,"API System"){
Component(TaskController,"TaskController")
Component(DateTaskController,"DateTaskController")
Component(DeadLineTaskController,"DeadLineTaskController")

Component(TaskService,"TaskService")
Component(DateTaskService,"DateTaskService")
Component(DeadLineTaskService,"DeadLineTaskService")

Component(TaskRepository,"TaskRepository")
Component(DateTaskRepository,"DateTaskRepository")
Component(DeadLineTaskRepository,"DeadLineTaskRepository")

Component(TaskEntity,"TaskEntity")
Component(DateTaskEntity,"DateTaskEntity")
Component(DeadLineTaskEntity,"DeadLineTaskEntity")

Component(TaskInterface,"TaskInterface")

Rel(TaskEntity,TaskInterface,"Implements")
Rel(DateTaskEntity,TaskEntity,"Extends")
Rel(DeadLineTaskEntity,TaskEntity,"Extends")

Rel(TaskRepository,database,"TCP/IP")
Rel(DateTaskRepository,database,"TCP/IP")
Rel(DeadLineTaskRepository,database,"TCP/IP")

Rel(TaskRepository,TaskEntity,"Uses")
Rel(DateTaskRepository,DateTaskEntity,"Uses")
Rel(DeadLineTaskRepository,DeadLineTaskEntity,"Uses")

Rel(TaskService,TaskRepository,"Uses")
Rel(DateTaskService,DateTaskRepository,"Uses")
Rel(DeadLineTaskService,DeadLineTaskRepository,"Uses")

Rel(TaskController,TaskService,"Uses")
Rel(DateTaskController,DateTaskService,"Uses")
Rel(DeadLineTaskController,DeadLineTaskService,"Uses")


}
@enduml
